# Processo Seletivo Analytica 2026 - **Grupo L**

# Requisitos
- Identificar linhas de ônibus “deficientes” em horário de pico
- Propor otimizações dessas linhas via remanejamento da frota
- Identificar critérios de remanejamento.
- EXTRA: Cruzar dados das “piores linhas” com os bairros, buscando os bairros mais afetados

# Preparação de dados

Para esse problema, realizamos uma busca dentre diversos datasets e encontramos os seguintes dados disponíveis. Abaixo, mostrarei uma visualização de algumas tabelas de dados.

# **OBS**:
Para visualizar outras tabelas csv nos códigos abaixo, basta substituir a string dentro de `caminho_dado` pelo caminho do arquivo que se deseja visualizar. Todos os arquivos utilizados estão na pasta `/content/drive/MyDrive/DadosAnalyticaPS2026-GrupoL`. Assim que tiver o e-mail de vocês, eu compartilho ela no drive.

## SMTR — Sistema Municipal de Transportes

Dados operacionais, financeiros e estruturais do sistema de transporte público do Rio de Janeiro. Filtrei alguns dados e, abaixo, segue a visualização de alguns que se mostraram mais relevantes para atender os requisitos.

### dashboard_bilhetagem_implantacao_jae
Monitoramento GPS Descrição: Dados agregados de localização de veículos por modal:

- BRT
- Ônibus (SPPO)
- Vans (STPL)
- VLT

In [4]:

import pandas as pd

caminho_dado = "/content/drive/MyDrive/DadosAnalyticaPS2026-GrupoL/dados brutos/dashboard_bilhetagem_implantacao_jae-20260430T211213Z-3-001/dashboard_bilhetagem_implantacao_jae/gps_agregado_onibus.csv"
df = pd.read_csv(caminho_dado)
display(df.head())
print(df.shape)

,operadora,id_validador,latitude,longitude,data,estado_equipamento,primeiro_datetime_gps,ultimo_datetime_gps,qtde_min_entre_a_prim_e_ultima_transmissao,qtde_min_distintos_houve_transmissao,qtde_registros_gps,qtde_registros_gps_georreferenciados,percentual_registros_gps_georreferenciados,percentual_transmissao_a_cada_min
0,CITY RIO ROTAS TURISTICAS LTDA,B35T020D00202175,-22.837801,-43.284966,2026-04-26,FECHADO,2026-04-26 00:00:01.126531,2026-04-26 00:04:01.197523,5,5,5,5,1.0,1.0
1,CITY RIO ROTAS TURISTICAS LTDA,B35T020D00204935,-22.836493,-43.285712,2026-04-26,FECHADO,2026-04-26 00:00:00.126985,2026-04-26 00:04:00.017346,5,5,5,5,1.0,1.0
2,CITY RIO ROTAS TURISTICAS LTDA,B35T020D00207037,-22.836385,-43.285718,2026-04-26,FECHADO,2026-04-26 00:00:13.989783,2026-04-26 00:04:13.625286,5,5,5,5,1.0,1.0
3,CITY RIO ROTAS TURISTICAS LTDA,B35T020D00201761,-22.837153,-43.284936,2026-04-26,FECHADO,2026-04-26 00:00:31.879626,2026-04-26 00:04:32.048613,5,5,5,5,1.0,1.0
4,CITY RIO ROTAS TURISTICAS LTDA,B35T020D00202807,-22.836716,-43.285729,2026-04-26,FECHADO,2026-04-26 00:00:49.664117,2026-04-26 00:04:49.78502,5,5,5,5,1.0,1.0

(3057, 14)

### gtfs
Base padronizada de transporte contendo:
- routes: linhas
- stops: paradas(id das paradas e localização). 485884 linhas
- trips: viagens (onibus, id das rotas e direção) 556360 linhas
- shapes: geometria das rotas (ponto de inicio/fim e formato). 13946 linhas. **aponta para shape**
- calendar + calendar_dates: operação temporal (obras, dias da semana, dia de inicio e término). 923 linhas e 34225 linhas
- ordem_servico: onibus, horarios de funcionamento, tamanho do trajedo ida/volta, total viagens ida/volta (dado o dia da semana) 113629 linhas

In [27]:
caminho_dado = "/content/drive/MyDrive/DadosAnalyticaPS2026-GrupoL/dados brutos/gtfs-20260430T211243Z-3-001/gtfs/trips.csv"
df = pd.read_csv(caminho_dado)
display(df.iloc[1:120])
print(df.shape)

,feed_version,feed_start_date,feed_end_date,route_id,service_id,trip_id,trip_headsign,trip_short_name,direction_id,block_id,shape_id,wheelchair_accessible,bikes_allowed,versao_modelo
1,2023-07-16,2023-07-16,2023-07-31,O0629AAA0A,D_REG,6f03c57c-081c-4881-8564-99956060043f,Irajá,629,1.0,NaN,ue02,NaN,NaN,201d79faee763526a030ff998bebea9782efe961
2,2025-10-12,2025-10-12,2025-10-25,O0774AAA0A,S_REG,54a62597-3e10-4f66-9315-0c33fcb8416a,Jardim América,774,0.0,NaN,i9sp,NaN,NaN,0e1fb230e34afc31d34d7f199f6f9038533b0de4
3,2025-05-01,2025-05-01,2025-05-23,O0112AAA0A,S_REG,6213293f-dedd-4559-8bff-885bbc471f24,Terminal Gentileza,112,1.0,NaN,O0112AAA0AVDU03,NaN,NaN,122abe77b87c75b8505fc679ef662556336ca16f
4,2025-11-08,2025-11-08,2025-11-18,O0343AAA0A,D_REG,c2189284-c0af-4d32-af87-c21af7d50827,Jardim Oceânico,343,1.0,NaN,j7v9,NaN,NaN,2a53b9c61f4b76fe07761a33083c714f9c35bcd0
5,2024-03-18,2024-03-18,2024-03-29,O0908AAA0A,S_REG,0505a7c1-71a8-4735-bfd4-b98bd3e080f6,Bonsucesso,908,0.0,NaN,O0908AAA0AIDU01,NaN,NaN,201d79faee763526a030ff998bebea9782efe961
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,2026-01-19,2026-01-19,2026-01-25,O0870AAA0A,U_REG,4d06c02b-55a7-4c67-87c1-3c50a76c8d5e,Sepetiba,870,1.0,NaN,n5hi,NaN,NaN,f7495a359559836032529b2d93bc4eff1a079265
116,2024-08-19,2024-08-19,2024-08-31,O0341AAA0A,U_REG,11941d41-5b6a-4049-8278-b8fa08fac423,Taquara,341,1.0,NaN,7zri,NaN,NaN,43b43fa561a2ae17398e297665179228b77f64aa
117,2023-10-24,2023-10-24,2023-10-31,fn03,S_REG,cb3ac48e-1918-4a1c-b5af-34758aaf8fd4,Pavuna,SR399,1.0,NaN,v25v,NaN,NaN,201d79faee763526a030ff998bebea9782efe961
118,2023-12-01,2023-12-01,2023-12-01,O0774AAA0A,S_REG,a4c321b8-19b7-4f96-b095-65430666fa00,Madureira,774,1.0,NaN,n7a5,NaN,NaN,201d79faee763526a030ff998bebea9782efe961
119,2025-05-24,2025-05-24,2025-05-24,O0801AAA0A,D_REG,6e77d9e9-0e72-46f7-a84c-a1eed494893e,Taquara,801,0.0,NaN,O0801AAA0AIDU01,NaN,NaN,bd3bdcb8b2b2c88ae81bcbe03f64ed235cc693d6

(556360, 14)

### br_rj_riodejaneiro_viagem_zirix
**TABELA CENTRAL**

Dados
- Horas de inicio e chegada de cada linha
- **Aponta para o shape id, veículo e número da linha**

Útil para calcular a duração de cada viagem dada a hora, que pode servir para criar um modelo preditivo que alimenta possíveis cálculos de otimizações.

In [20]:
caminho_dado = "/content/drive/MyDrive/DadosAnalyticaPS2026-GrupoL/dados brutos/br_rj_riodejaneiro_viagem_zirix-20260430T211251Z-3-001/br_rj_riodejaneiro_viagem_zirix/viagem_informada.csv"
df = pd.read_csv(caminho_dado)
display(df.iloc[1:120])
print(df.shape)

,data,datetime_partida,datetime_chegada,datetime_processamento,datetime_captura,id_veiculo,trip_id,route_id,shape_id,servico,sentido,id_viagem,versao,datetime_ultima_atualizacao
1,2024-12-08,2024-12-08 18:23:39,2024-12-08 19:34:38,2024-12-08 19:34:40,2024-12-08 19:40:00,B10003,NaN,186,421,901,Ida,B10003_901_I_421_20241208182339,0797b1e917d2ed2d50489a35abd2b87dcab54b55,2024-12-10 01:34:25.331602
2,2025-09-19,2025-09-19 06:41:53,2025-09-19 08:27:23,2025-09-19 08:27:25,2025-09-19 08:40:00,D13012,NaN,O0383AAA0A,34402958-de24-498e-b913-3f70f5311747,383,Volta,D13012_383_V_34402958-de24-498e-b913-3f70f5311...,06f003ebcace75a8702b05d063933a3ac6edc0f8,2025-09-26 01:32:16.328995
3,2025-06-27,2025-06-27 04:53:31,2025-06-27 05:11:55,2025-06-27 05:11:58,2025-06-27 05:20:00,A48056,NaN,O0202AAA0A,1760,202,Ida,A48056_202_I_1760_20250627045331,477e243683cf4516bd39ad4ee8ff21793b78279c,2025-07-02 01:32:34.960347
4,2025-02-19,2025-02-19 07:15:43,2025-02-19 09:27:43,2025-02-19 20:17:14,2025-02-19 20:30:00,C47638,NaN,O0390AAA0A,5au5,390,Ida,C47638_390_I_5au5_20250219071543,8b2a8320de08cc624e12dbbd49f8e02da750444f,2025-02-28 01:34:03.91567
5,2025-05-14,2025-05-14 16:41:44,2025-05-14 18:18:46,2025-05-14 18:18:53,2025-05-14 18:30:00,A41124,NaN,O0108AAA0A,tu4h,108,Volta,A41124_108_V_tu4h_20250514164144,d349769b0baa95c568e15e5e7172f14bf2a1aeeb,2025-05-17 01:32:41.649249
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,2024-09-09,2024-09-09 06:04:01,2024-09-09 06:57:31,2024-09-09 06:57:33,2024-09-09 07:10:00,B58028,NaN,O0313AAA0A,rp0h,313,Ida,B58028_313_I_rp0h_20240909060401,01e2893bb9f7740e6a8cbef6e3cc41023eb76c8b,2024-09-11 01:32:31.606445
116,2025-06-10,2025-06-10 10:34:37,2025-06-10 11:04:40,2025-06-10 11:04:40,2025-06-10 11:10:00,D12061,NaN,O0850AAA0A,O0850AAA0AIDU01,850,Ida,D12061_850_I_O0850AAA0AIDU01_20250610103437,70ea3e327bf97de86d1ca8ee6dcea82672b36d17,2025-06-16 01:40:32.326528
117,2025-12-19,2025-12-19 17:19:18,2025-12-19 18:17:48,2025-12-19 18:17:51,2025-12-19 18:30:00,D86092,NaN,O0871AAA0A,snbu,871,Ida,D86092_871_I_snbu_20251219171918,8cece5d825148f36f9f3cf05b7179fc5b7fd6302,2025-12-23 01:32:23.658456
118,2025-01-22,2025-01-22 13:15:21,2025-01-22 14:23:51,2025-01-22 14:23:54,2025-01-22 14:30:00,B31120,NaN,149,370,497,Volta,B31120_497_V_370_20250122131521,9cff872313ce314dcd97d4cecb0e3b9b95d3fc2a,2025-01-31 01:35:15.840984
119,2025-08-27,2025-08-27 15:32:59,2025-08-27 16:25:59,2025-08-27 16:26:02,2025-08-27 16:40:00,A29021,NaN,O0474AAV0A,qppd,SV474,Ida,A29021_SV474_I_qppd_20250827153259,04aa8059f77fb4f8cb180398dd024c83f9afd352,2025-09-02 01:32:57.056916

(256725, 14)

### veiculo
Dados dos veículos do sistema:

- Licenciamento: id de veículo, data da última vistoria, tecnologia, id chassi. 222625 linhas.
- solicitação de licenciamento: solicitações realizadas. Acredito que não está no escopo
- registro agente verao: Acredito que não está no escopo
# - Operação diária
- Inspeções
- Condições operacionais

In [26]:
caminho_dado = "/content/drive/MyDrive/DadosAnalyticaPS2026-GrupoL/dados brutos/veiculo-20260430T211305Z-3-001/veiculo/sppo_veiculo_dia.csv"
df = pd.read_csv(caminho_dado)
display(df.iloc[1:120])
print(df.shape)

,data,id_veiculo,indicadores,status,tecnologia,placa,data_licenciamento,data_infracao,datetime_ultima_atualizacao,versao
1,2024-07-29,A50052,"{""indicador_ar_condicionado"":true,""indicador_a...",Licenciado com ar e não autuado,NaN,NaN,NaN,NaN,2024-07-29 00:00:00,389645e94331a6482e15e038430440ff7db39778
2,2023-06-16,C47893,"{""indicador_ar_condicionado"":true,""indicador_a...",Licenciado com ar e não autuado (023.II),NaN,NaN,NaN,NaN,2023-06-16 00:00:00,NaN
3,2023-03-05,C27106,"{""indicador_ar_condicionado"":true,""indicador_a...",Licenciado com ar e autuado (023.II),NaN,NaN,NaN,NaN,2023-03-05 00:00:00,NaN
4,2023-10-15,D13045,"{""indicador_ar_condicionado"":true,""indicador_a...",Licenciado com ar e não autuado,NaN,NaN,NaN,NaN,2025-07-08 19:52:01.168434,432fd8b43c8d00bd72b10115bcf6649a74371543
5,2023-07-20,B32611,"{""indicador_ar_condicionado"":false,""indicador_...",Licenciado sem ar e não autuado,NaN,NaN,NaN,NaN,2023-07-20 00:00:00,NaN
...,...,...,...,...,...,...,...,...,...,...
115,2024-03-06,C30371,"{""indicador_ar_condicionado"":true,""indicador_a...",Licenciado com ar e não autuado,NaN,NaN,NaN,NaN,2025-07-09 15:19:55.514817,21b44fea9b6195ab051abb2902eb454531b44db2
116,2023-03-11,B28577,"{""indicador_ar_condicionado"":true,""indicador_a...",Licenciado com ar e não autuado (023.II),NaN,NaN,NaN,NaN,2023-03-11 00:00:00,NaN
117,2023-02-14,D86144,"{""indicador_ar_condicionado"":true,""indicador_a...",Licenciado com ar e não autuado (023.II),NaN,NaN,NaN,NaN,2023-02-14 00:00:00,NaN
118,2024-07-10,B32716,"{""indicador_ar_condicionado"":true,""indicador_a...",Licenciado com ar e não autuado,NaN,NaN,NaN,NaN,2024-07-10 00:00:00,7f82815acd73838af72ee1ed091739d16d51b92f
119,2023-08-10,B32541,"{""indicador_ar_condicionado"":true,""indicador_a...",Licenciado com ar e não autuado,NaN,NaN,NaN,NaN,2023-08-10 00:00:00,d3cf5cd05a1af054e6ffa7bfcd4597722a07c258

(136939, 10)