In [ ]:
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.preprocessing import LabelEncoder
import joblib

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# Treinamento do Modelo

No colab anterior, realizei as etapas de coleta, análise exploratória e processamento dos dados do csv. Agora, temos exatamente os dados limpos com tratamento para outliers.

Utilizaremos o modelo **RandomForestRegressor**.

Iremos separar 80% das viagens iniciais para treinar o modelo e os restantes 20% para testar a acurácia dele.

In [ ]:
caminho_df_final = "/content/drive/MyDrive/DadosAnalyticaPS2026-GrupoL/dados tratados/df_final.csv"
df = pd.read_csv(caminho_df_final)

#Convertendo a string de linha para um codigo numerico via label encoding
le_linha = LabelEncoder()
df['servico'] = le_linha.fit_transform(df['servico'])

display(df.head())
display(df.describe())
display(df.info())

,servico,sentido,duracao,mes_viagem,dia_viagem,hora_partida,dia_semana,eh_feriado
0,69,0,62.500000,2,25,361,2,0
1,69,1,60.383333,9,24,474,2,0
2,69,0,53.500000,3,21,375,5,0
3,69,0,105.016667,11,13,1033,3,0
4,69,0,55.050000,3,20,271,3,0

,servico,sentido,duracao,mes_viagem,dia_viagem,hora_partida,dia_semana,eh_feriado
count,222612.000000,222612.000000,222612.000000,222612.000000,222612.000000,222612.000000,222612.000000,222612.0
mean,131.631655,0.504851,61.090174,6.135375,15.655396,769.357613,2.689424,0.0
std,78.048716,0.499978,28.323484,3.619840,8.767378,330.150184,1.886227,0.0
min,0.000000,0.000000,5.000000,1.000000,1.000000,0.000000,0.000000,0.0
25%,65.000000,0.000000,40.100000,3.000000,8.000000,489.000000,1.000000,0.0
50%,126.000000,1.000000,59.083333,6.000000,15.000000,757.000000,3.000000,0.0
75%,201.000000,1.000000,78.533333,9.000000,23.000000,1042.000000,4.000000,0.0
max,280.000000,1.000000,345.483333,12.000000,31.000000,1439.000000,6.000000,0.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 222612 entries, 0 to 222611
Data columns (total 8 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   servico       222612 non-null  int64
 1   sentido       222612 non-null  int64
 2   duracao       222612 non-null  float64
 3   mes_viagem    222612 non-null  int64
 4   dia_viagem    222612 non-null  int64
 5   hora_partida  222612 non-null  int64
 6   dia_semana    222612 non-null  int64
 7   eh_feriado    222612 non-null  int64
dtypes: float64(1), int64(7)
memory usage: 13.6 MB

None

In [ ]:

#os dados p treinar e respostas do modelo
X = df.drop(['duracao'], axis=1)
y = df['duracao']

#em seguida dividimos o dataset em 80% treinamento e 20% teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=19)
rfr = RandomForestRegressor(random_state=13)

#treinamento do modelo
rfr.fit(X_train, y_train)

#guardamos a previsao em uma variavel e depois avaliamos a acuracia do modelo
y_pred = rfr.predict(X_test)

print(mean_absolute_error(y_test, y_pred))
print(mean_squared_error(y_test, y_pred))
print(r2_score(y_test, y_pred))

#armazenando o modelo em um arquivo e salvando no drive
caminho_modelo = "/content/drive/MyDrive/DadosAnalyticaPS2026-GrupoL/modeloML/modelo.pkl"
joblib.dump(rfr, caminho_modelo)
joblib.dump(le_linha, '/content/drive/MyDrive/DadosAnalyticaPS2026-GrupoL/modeloML/le_linha.pkl') #salvando o label encoder

7.063809653892103
111.81765086871863
0.861715048506166

['/content/drive/MyDrive/DadosAnalyticaPS2026-GrupoL/modeloML/le_linha.pkl']